### ISSUE TITLE
Washingtonpost.com no longer works

### ISSUE THREAD

**Issue by prech** [bpc-clone/bpc_chrome_support#19] opened 2024-04-30 05:09 UTC
Describe issue/request: 
Wapo pages not loading with BPC 

Link of paywalled article: 
https://www.washingtonpost.com/world/2024/04/29/india-assassination-raw-sikhs-modi/
https://www.washingtonpost.com/nation/2024/04/29/charlotte-shooting-police-officers-nc/
https://www.washingtonpost.com/nation/2024/04/29/ralph-yarl-lawsuit-andrew-lester/

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
Clear cookies. Disable adblockers. Select pages do load on Archive sites (https://www.washingtonpost.com/world/2024/04/29/india-assassination-raw-sikhs-modi/), but not others

Browser (main version): 
Chrome 124.0.6367.91 and Kiwi 124.0.6327.4 (Android)

BPC-extension version (number): 
3.6.6.0

Screenshot:
![image](https://github.com/bpc-clone/bypass-paywalls-chrome-clean/assets/8314103/895506a2-82ee-4473-9cd3-0caf4e911a90)

**Comment by bpc-clone** [comment] 2024-04-30 06:45
Site fixed in latest master/update rules (or next release).

**Comment by nhan000** [comment] 2024-05-02 03:20
@prech May I ask how you have the dark mode?

**Comment by prech** [comment] 2024-05-02 05:33
> @prech May I ask how you have the dark mode?

@nhan000 -- I use the Dark Reader extension: https://chromewebstore.google.com/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh

Works well on mobile, too. But it does conflict with some sites, like it has to be disabled with Bloomberg.com when using BPC

**Closed as completed** 2024-05-06 06:01 UTC
Labels: fixed

**Comment by prech** [comment] 2024-05-12 21:17
Hi @bpc-clone 

Very odd, but it seems something with Wapo has changed and stopped loading since earlier in the week. Archive still works, and pages do load in Kiwi, just not desktop Chrome. Also tried with Incognito and with VPN.

I've tried with both BPC v3.6.7.1 and v3.6.8.0.

Example:
https://www.washingtonpost.com/science/2024/05/11/northern-lights-aurora-natural-wonders/

![image](https://github.com/bpc-clone/bypass-paywalls-chrome-clean/assets/8314103/5e328ca7-8693-479f-9173-71875faa1f8c)

More examples:
https://www.washingtonpost.com/science/2024/05/07/sperm-whale-alphabet-clicks/
https://www.washingtonpost.com/wellness/2024/05/12/down-syndrome-regression-disorder-mothers-support/

**Comment by jsfs11** [comment] 2024-05-13 02:08
@prech I can't reproduce on desktop chrome and BPC v3.6.8.0 using the links you provided, they all work fine for me.

**Comment by prech** [comment] 2024-05-13 03:59
> @prech I can't reproduce on desktop chrome and BPC v3.6.8.0 using the links you provided, they all work fine for me.

Thanks @jsfs11 -- this is very odd.

I was worried it may be my Chrome (v124.0.6367.202) install, so I did a Reset Settings, including reinstalling extensions and clearing all cookies/cache, but I'm still experiencing this specifically with washingtonpost.com

I installed BPC with Chrome Beta (v125.0.6422.41) and Chrome Dev (v126.0.6452.3) and both were able to load Wapo, so perhaps my Chrome is corrupted somewhere...

**Comment by prech** [comment] 2024-06-04 02:52
> I was worried it may be my Chrome (v124.0.6367.202) install, so I did a Reset Settings, including reinstalling extensions and clearing all cookies/cache, but I'm still experiencing this specifically with washingtonpost.com
> 
> I installed BPC with Chrome Beta (v125.0.6422.41) and Chrome Dev (v126.0.6452.3) and both were able to load Wapo, so perhaps my Chrome is corrupted somewhere...

Very interestingly, the update to BPC v3.7.1.0 has resolved my issues with Washingtonpost.com

Not sure what may have been part of the update, but I no longer have to use a different iteration of Chrome to load Wapo! Even BPC v3.7.0.0 was not loading the full text at Wapo for me.
